name = "PHYS5336"
uuid = "2b74c331-0f8e-452d-a472-74211e574184"
authors = ["John Waczak", "David Lary"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
